name: cs442_mp4
description: Flashcards
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.5.0'

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.11
  provider: ^6.0.5
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flashcards.json
